### ISSUE TITLE
Error in collection

### ISSUE THREAD

**Issue by sgoggins** [Euphorbium/cancerforums-scraper#1]
Kicked it off on my server and got this error:

Traceback (most recent call last):
  File "scrape.py", line 49, in <module>
    print thread.text
UnicodeEncodeError: 'ascii' codec can't encode character u'\x92' in position 46: ordinal not in range(128)

Error was repeated on the second attempt.  

Thanks!

**Comment by Euphorbium** [comment]
Fixed.
