### ISSUE TITLE
I think a small indentation error

### ISSUE THREAD

**Issue by sgoggins** [Euphorbium/cancerforums-scraper#2]
[gogginss@sociotechnical-missouri-edu cancerforums-scraper]$ cat sean.err
nohup: ignoring input
  File "scrape.py", line 23
    unique = qid+'_'+str(id-1)
    ^
IndentationError: unexpected indent

**Comment by Euphorbium** [comment]
fixed. Used a different editor, which did not translate tabs to spaces correctly.
